[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  VITE_CSV_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vTkYnbouBvZA9xjMXRdEAWgO7lZSEZDAC10fp9p5XpsEMivGQ8v5XWUHtS73hIhDzb6_94_uYApGzif/pub?gid=0&single=true&output=csv"
  VITE_STATE_NAME = "Victoria"

[context.deploy-preview.environment]
  VITE_CSV_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vTkYnbouBvZA9xjMXRdEAWgO7lZSEZDAC10fp9p5XpsEMivGQ8v5XWUHtS73hIhDzb6_94_uYApGzif/pub?gid=0&single=true&output=csv"
  VITE_STATE_NAME = "Victoria"

[context.branch-deploy.environment]
  VITE_CSV_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vTkYnbouBvZA9xjMXRdEAWgO7lZSEZDAC10fp9p5XpsEMivGQ8v5XWUHtS73hIhDzb6_94_uYApGzif/pub?gid=0&single=true&output=csv"
  VITE_STATE_NAME = "Victoria"

[context.dev.environment]
  VITE_CSV_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vTkYnbouBvZA9xjMXRdEAWgO7lZSEZDAC10fp9p5XpsEMivGQ8v5XWUHtS73hIhDzb6_94_uYApGzif/pub?gid=0&single=true&output=csv"
  VITE_STATE_NAME = "Victoria"
